name: Benchmark

on:
  push:
    branches:
      - master

jobs:
  benchmark:
    name: Performance comparison
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Install gulp
        run: npm install --global gulp
      - name: Build
        run: |
          npm install
          gulp lint-js
          gulp build
      - name: Test
        run: node test/index.js
      - name: Reset
        run: git reset --hard
      - name: Run benchmark
        run: node test/hexbench.js | tee output.txt
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Benchmark
          # What benchmark tool the output.txt came from
          tool: 'benchmarkjs'
          # Where the output from the benchmark tool is stored
          output-file-path: output.txt
          # Personal access token to deploy GitHub Pages branch
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          # Push and deploy GitHub pages branch automatically
          auto-push: true